# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# 沙箱代理
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1|::1|.svc|.cluster.local
systemProp.https.nonProxyHosts=localhost|127.0.0.1|::1|.svc|.cluster.local

# Parchment mappings
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.1.3
forge_version_range=[47.1.3,)
loader_version_range=[47,)

## Mod Properties
mod_id=land_economy_mod_1783600667
mod_name=\u9886\u5730\u7ecf\u6d4e
mod_license=All Rights Reserved
mod_version=1.8.0
mod_group_id=cn.autoforged.land_economy_mod_1783600667
mod_authors=m20091112@126.com
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
org.gradle.java.installations.auto-download=true